# Generated by Django 5.1.2 on 2024-10-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_fullname', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=50)),
                ('birth_date', models.DateField()),
                ('enrollment_date', models.DateField()),
            ],
        ),
    ]
