# Generated by Django 5.1.1 on 2024-10-26 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=100)),
                ('class_time', models.DateTimeField()),
                ('room_number', models.CharField(max_length=10)),
                ('max_students', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samsapp.student')),
            ],
        ),
    ]
