# Generated by Django 5.1.1 on 2024-11-21 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsapp', '0003_classlist_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Present'), ('L', 'Late'), ('A', 'Absent')], default='A', max_length=1)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samsapp.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samsapp.student')),
            ],
        ),
    ]
