# Generated by Django 5.1.1 on 2024-12-12 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samsapp', '0007_alter_attendance_class_name_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='samsapp.class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
