# Generated by Django 5.1.1 on 2024-12-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samsapp', '0009_remove_student_student_id_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='student_id',
        ),
    ]
